"""Independent final regression gate — the last line of defence.

Acceptance criteria under test (each assertion can fail on a real regression):

  1. ``pytest tests/`` exits 0 — the full suite passes when run as a fresh subprocess.
  2. Acceptance script exits 0 **and** the dual-lens column text is present in stdout:
       ``#### LEFT``  and  ``#### RIGHT``  (the "lens text") must appear.
  3. ``verdict_brief.txt`` as committed/generated on disk contains exactly:
       line 1: ``DUAL_LENS: Y``
       line 2: ``SPIN_PCT: Y``
       line 3: ``MARKET: Y``

Design note: to prevent infinite subprocess recursion the meta-pytest run
excludes this file plus every other file that also spawns a pytest subprocess.
Every assertion here is capable of failing on a genuine code regression — no
trivially-true checks.
"""

from __future__ import annotations

import os
import re
import subprocess
import sys
from pathlib import Path

import pytest

PROJECT_ROOT = Path(__file__).parent.parent
ACCEPTANCE_FILE = PROJECT_ROOT / "acceptance"
VERDICT_FILE = PROJECT_ROOT / "verdict_brief.txt"

THIS_FILE = Path(__file__).name

# All test files known to spawn a pytest subprocess — exclude all to break cycles.
# Including test_acceptance_regression_guard.py which also spawns pytest via its
# pytest_x_result fixture; omitting it would create a 3-level subprocess chain.
_PYTEST_META_FILES = [
    THIS_FILE,
    "test_regression_guard.py",
    "test_pytest_acceptance_regression.py",
    "test_independent_subprocess_guard.py",
    "test_final_regression_guard.py",
    "test_acceptance_regression_guard.py",
]


# ---------------------------------------------------------------------------
# Shared helpers
# ---------------------------------------------------------------------------


def _stub_env() -> dict[str, str]:
    """Force stub LLM and fixture RSS so no live network calls are needed."""
    return {
        **os.environ,
        "SM_LLM_BACKEND": "stub",
        "SM_SOURCES": "tests/fixtures/rss_sample.xml",
    }


# ---------------------------------------------------------------------------
# Module-scoped fixtures — each subprocess runs exactly once per test session
# ---------------------------------------------------------------------------


@pytest.fixture(scope="module")
def pytest_result() -> subprocess.CompletedProcess:
    """Run pytest as a subprocess, excluding all files that themselves spawn pytest."""
    ignore_flags = [f"--ignore=tests/{f}" for f in _PYTEST_META_FILES]
    return subprocess.run(
        [
            sys.executable,
            "-m", "pytest",
            "tests/",
            *ignore_flags,
            "-q",
            "--tb=short",
        ],
        capture_output=True,
        cwd=PROJECT_ROOT,
        env=_stub_env(),
        timeout=600,
    )


@pytest.fixture(scope="module")
def acceptance_result() -> subprocess.CompletedProcess:
    """Run the acceptance script verbatim and capture stdout, stderr, and returncode."""
    cmd = ACCEPTANCE_FILE.read_text().strip()
    return subprocess.run(
        cmd,
        shell=True,
        capture_output=True,
        timeout=120,
        cwd=PROJECT_ROOT,
    )


@pytest.fixture(scope="module")
def acceptance_stdout(acceptance_result: subprocess.CompletedProcess) -> str:
    return acceptance_result.stdout.decode(errors="replace")


@pytest.fixture(scope="module")
def verdict_lines() -> list[str]:
    """Non-empty, stripped lines from verdict_brief.txt as it exists on disk."""
    assert VERDICT_FILE.exists(), (
        f"verdict_brief.txt not found at {VERDICT_FILE}; "
        "the file must be generated by evidence.py before running this gate"
    )
    return [l.rstrip() for l in VERDICT_FILE.read_text().splitlines() if l.strip()]


# ---------------------------------------------------------------------------
# 1. pytest subprocess: returncode 0
# ---------------------------------------------------------------------------


class TestPytestSubprocessReturncodeZero:
    """Criterion 1: pytest tests/ must exit 0 when run as a fresh subprocess."""

    def test_returncode_is_zero(
        self, pytest_result: subprocess.CompletedProcess
    ) -> None:
        """Primary gate: a non-zero returncode means at least one test failed."""
        stdout = pytest_result.stdout.decode(errors="replace")
        stderr = pytest_result.stderr.decode(errors="replace")
        assert pytest_result.returncode == 0, (
            f"pytest subprocess exited {pytest_result.returncode}; expected 0.\n"
            f"--- stdout (tail) ---\n{stdout[-3000:]}\n"
            f"--- stderr (tail) ---\n{stderr[-500:]}"
        )

    def test_at_least_one_test_passed(
        self, pytest_result: subprocess.CompletedProcess
    ) -> None:
        """A returncode-0 with zero collected tests would silently hide a broken conftest."""
        output = pytest_result.stdout.decode(errors="replace")
        matches = re.findall(r"(\d+) passed", output)
        assert matches, (
            f"'N passed' not found in pytest -q output — no tests may have run.\n"
            f"Output tail:\n{output[-1000:]}"
        )
        count = int(matches[-1])
        assert count >= 1, (
            f"Expected at least 1 test to pass; got {count}"
        )

    def test_no_collection_errors(
        self, pytest_result: subprocess.CompletedProcess
    ) -> None:
        """Collection errors cause a non-zero exit but also leave an explicit marker."""
        combined = (
            pytest_result.stdout.decode(errors="replace")
            + pytest_result.stderr.decode(errors="replace")
        )
        assert "ERROR collecting" not in combined, (
            f"Collection errors detected in pytest output.\n"
            f"First 2000 chars:\n{combined[:2000]}"
        )

    def test_no_import_errors(
        self, pytest_result: subprocess.CompletedProcess
    ) -> None:
        """An ImportError during collection or test run means a broken module."""
        combined = (
            pytest_result.stdout.decode(errors="replace")
            + pytest_result.stderr.decode(errors="replace")
        )
        assert "ImportError" not in combined, (
            f"ImportError detected in pytest output — a module failed to import.\n"
            f"First 2000 chars:\n{combined[:2000]}"
        )

    def test_no_failures_in_summary(
        self, pytest_result: subprocess.CompletedProcess
    ) -> None:
        """The -q summary must not contain 'failed' when returncode is 0."""
        output = pytest_result.stdout.decode(errors="replace")
        # Only assert when rc=0 to avoid redundant messaging on an already-failed run.
        if pytest_result.returncode == 0:
            lower = output.lower()
            # "failed" may appear in test names; only look at the summary block.
            summary_idx = output.rfind("=====")
            summary = output[summary_idx:] if summary_idx >= 0 else output[-500:]
            assert "failed" not in summary.lower(), (
                f"'failed' keyword found in pytest summary block:\n{summary}"
            )

    def test_collects_minimum_test_count(
        self, pytest_result: subprocess.CompletedProcess
    ) -> None:
        """A count well below the known suite size signals a broken collection."""
        output = pytest_result.stdout.decode(errors="replace")
        matches = re.findall(r"(\d+) passed", output)
        if not matches:
            return  # already caught by test_at_least_one_test_passed
        count = int(matches[-1])
        assert count >= 30, (
            f"Expected at least 30 tests to pass (sanity floor); got {count}.\n"
            f"Output tail:\n{output[-1000:]}"
        )


# ---------------------------------------------------------------------------
# 2. Acceptance script subprocess: returncode 0 + lens text in stdout
# ---------------------------------------------------------------------------


class TestAcceptanceSubprocessReturncodeAndLensText:
    """Criterion 2: acceptance script must exit 0 and emit dual-lens column text."""

    def test_returncode_is_zero(
        self, acceptance_result: subprocess.CompletedProcess
    ) -> None:
        """Primary gate: a non-zero returncode means at least one subcommand failed."""
        stdout = acceptance_result.stdout.decode(errors="replace")
        stderr = acceptance_result.stderr.decode(errors="replace")
        assert acceptance_result.returncode == 0, (
            f"Acceptance script exited {acceptance_result.returncode}; expected 0.\n"
            f"Both 'once' and 'digest-dry-run' subcommands must succeed.\n"
            f"stdout (first 2000):\n{stdout[:2000]}\n"
            f"stderr (first 500):\n{stderr[:500]}"
        )

    def test_left_lens_text_in_stdout(self, acceptance_stdout: str) -> None:
        """'#### LEFT' must appear in acceptance stdout — the left lens column heading."""
        assert "#### LEFT" in acceptance_stdout, (
            "Acceptance stdout must contain '#### LEFT' lens column heading.\n"
            "This is emitted by _print_dual_lens() in the 'once' subcommand.\n"
            f"Acceptance stdout (first 2000 chars):\n{acceptance_stdout[:2000]}"
        )

    def test_right_lens_text_in_stdout(self, acceptance_stdout: str) -> None:
        """'#### RIGHT' must appear in acceptance stdout — the right lens column heading."""
        assert "#### RIGHT" in acceptance_stdout, (
            "Acceptance stdout must contain '#### RIGHT' lens column heading.\n"
            "This is emitted by _print_dual_lens() in the 'once' subcommand.\n"
            f"Acceptance stdout (first 2000 chars):\n{acceptance_stdout[:2000]}"
        )

    def test_left_heading_is_exact_h4(self, acceptance_stdout: str) -> None:
        """'#### LEFT' must appear at the start of a line (proper H4, not inline prose)."""
        h4_left = [l for l in acceptance_stdout.splitlines() if l.startswith("#### LEFT")]
        assert h4_left, (
            "No line starting with '#### LEFT' found in acceptance stdout.\n"
            "The left column heading must be a proper H4 line."
        )

    def test_right_heading_is_exact_h4(self, acceptance_stdout: str) -> None:
        """'#### RIGHT' must appear at the start of a line (proper H4, not inline prose)."""
        h4_right = [l for l in acceptance_stdout.splitlines() if l.startswith("#### RIGHT")]
        assert h4_right, (
            "No line starting with '#### RIGHT' found in acceptance stdout.\n"
            "The right column heading must be a proper H4 line."
        )

    def test_both_lens_headings_inside_dual_lens_block(self, acceptance_stdout: str) -> None:
        """Both lens headings must appear AFTER the '## DUAL-LENS EVENTS' block header."""
        idx = acceptance_stdout.find("## DUAL-LENS EVENTS")
        assert idx >= 0, (
            "Acceptance stdout must contain '## DUAL-LENS EVENTS' block header"
        )
        block_text = acceptance_stdout[idx:]
        assert "#### LEFT" in block_text, (
            "'#### LEFT' must appear inside the DUAL-LENS EVENTS block"
        )
        assert "#### RIGHT" in block_text, (
            "'#### RIGHT' must appear inside the DUAL-LENS EVENTS block"
        )

    def test_left_column_contains_article_bullet(self, acceptance_stdout: str) -> None:
        """A '- ...' bullet must follow '#### LEFT' — the column must not be empty."""
        lines = acceptance_stdout.splitlines()
        in_left = False
        for line in lines:
            if line.startswith("#### LEFT"):
                in_left = True
                continue
            if in_left:
                if line.startswith("- "):
                    return  # found a bullet — test passes
                if line.startswith("#"):
                    break
        pytest.fail(
            "No '- ...' article bullet found under '#### LEFT' heading in acceptance stdout"
        )

    def test_right_column_contains_article_bullet(self, acceptance_stdout: str) -> None:
        """A '- ...' bullet must follow '#### RIGHT' — the column must not be empty."""
        lines = acceptance_stdout.splitlines()
        in_right = False
        for line in lines:
            if line.startswith("#### RIGHT"):
                in_right = True
                continue
            if in_right:
                if line.startswith("- "):
                    return  # found a bullet — test passes
                if line.startswith("#"):
                    break
        pytest.fail(
            "No '- ...' article bullet found under '#### RIGHT' heading in acceptance stdout"
        )

    def test_spin_pct_annotation_in_stdout(self, acceptance_stdout: str) -> None:
        """'spin_pct:' must appear in acceptance stdout — per-article spin annotation."""
        assert "spin_pct:" in acceptance_stdout, (
            "Acceptance stdout must contain 'spin_pct:' annotation in article bullets"
        )

    def test_spin_pct_value_is_numeric_float(self, acceptance_stdout: str) -> None:
        """spin_pct values must be parseable floats in the [0, 100] range."""
        matches = re.findall(r"spin_pct:\s*([\d.]+)%", acceptance_stdout)
        assert matches, (
            "No 'spin_pct: N.N%' pattern found in acceptance stdout"
        )
        for raw in matches:
            val = float(raw)
            assert 0.0 <= val <= 100.0, (
                f"spin_pct value {val}% is outside the valid 0–100 range"
            )

    def test_situation_monitor_heading_present(self, acceptance_stdout: str) -> None:
        """The output must begin with a 'Situation Monitor' heading."""
        assert "Situation Monitor" in acceptance_stdout, (
            "Acceptance stdout must contain the 'Situation Monitor' top-level heading"
        )

    def test_no_python_traceback(self, acceptance_stdout: str) -> None:
        """A Python traceback in stdout indicates an unhandled exception — not acceptable."""
        assert "Traceback (most recent call last)" not in acceptance_stdout, (
            "Acceptance stdout must not contain a Python traceback"
        )

    def test_top_stories_section_present(self, acceptance_stdout: str) -> None:
        """The digest-dry-run command (second half of acceptance) must emit *Top Stories*."""
        assert "*Top Stories*" in acceptance_stdout, (
            "Acceptance stdout must contain '*Top Stories*' — "
            "emitted by the 'digest-dry-run' subcommand"
        )

    def test_acceptance_file_references_both_subcommands(self) -> None:
        """The acceptance file must invoke both 'once' and 'digest-dry-run'."""
        text = ACCEPTANCE_FILE.read_text()
        assert " once " in text, (
            "acceptance file must invoke the 'once' subcommand"
        )
        assert "digest-dry-run" in text, (
            "acceptance file must invoke the 'digest-dry-run' subcommand"
        )


# ---------------------------------------------------------------------------
# 3. verdict_brief.txt: DUAL_LENS: Y, SPIN_PCT: Y, MARKET: Y
# ---------------------------------------------------------------------------


class TestVerdictBriefConfirmsAllThree:
    """Criterion 3: verdict_brief.txt must confirm DUAL_LENS: Y, SPIN_PCT: Y, MARKET: Y."""

    def test_verdict_file_exists(self) -> None:
        assert VERDICT_FILE.exists(), (
            f"verdict_brief.txt not found at {VERDICT_FILE}.\n"
            "Run evidence.py to generate it before executing this gate."
        )

    def test_verdict_file_is_non_empty(self) -> None:
        assert VERDICT_FILE.read_text().strip(), (
            "verdict_brief.txt must not be empty"
        )

    def test_verdict_has_at_least_three_lines(self, verdict_lines: list[str]) -> None:
        assert len(verdict_lines) >= 3, (
            f"verdict_brief.txt must contain at least 3 non-empty lines; "
            f"got {len(verdict_lines)}: {verdict_lines!r}"
        )

    def test_dual_lens_y_on_line_one(self, verdict_lines: list[str]) -> None:
        """Line 1 must be exactly 'DUAL_LENS: Y' — confirms dual-lens pipeline captured both sides."""
        assert len(verdict_lines) >= 1, "verdict_brief.txt has no content"
        assert verdict_lines[0] == "DUAL_LENS: Y", (
            f"verdict_brief.txt line 1 must be 'DUAL_LENS: Y'; "
            f"got {verdict_lines[0]!r}.\n"
            "DUAL_LENS is 'Y' only when the pipeline has articles in BOTH left and right buckets."
        )

    def test_spin_pct_y_on_line_two(self, verdict_lines: list[str]) -> None:
        """Line 2 must be exactly 'SPIN_PCT: Y' — confirms spin estimation ran on at least one article."""
        assert len(verdict_lines) >= 2, (
            "verdict_brief.txt must have at least 2 non-empty lines"
        )
        assert verdict_lines[1] == "SPIN_PCT: Y", (
            f"verdict_brief.txt line 2 must be 'SPIN_PCT: Y'; "
            f"got {verdict_lines[1]!r}.\n"
            "SPIN_PCT is 'Y' only when spin estimation produced at least one spin_pct value."
        )

    def test_market_y_on_line_three(self, verdict_lines: list[str]) -> None:
        """Line 3 must be exactly 'MARKET: Y' — confirms fetch_practical_movers returned data."""
        assert len(verdict_lines) >= 3, (
            "verdict_brief.txt must have at least 3 non-empty lines"
        )
        assert verdict_lines[2] == "MARKET: Y", (
            f"verdict_brief.txt line 3 must be 'MARKET: Y'; "
            f"got {verdict_lines[2]!r}.\n"
            "MARKET is 'Y' only when fetch_practical_movers() returns at least one mover."
        )

    def test_all_three_criteria_composite(self, verdict_lines: list[str]) -> None:
        """Composite check: all three lines correct in a single assertion for quick triage."""
        assert len(verdict_lines) >= 3, (
            f"verdict_brief.txt must have at least 3 lines; got {len(verdict_lines)}"
        )
        expected = ["DUAL_LENS: Y", "SPIN_PCT: Y", "MARKET: Y"]
        for i, exp in enumerate(expected):
            got = verdict_lines[i]
            assert got == exp, (
                f"verdict_brief.txt line {i + 1}: expected {exp!r}, got {got!r}"
            )

    def test_values_are_y_not_n(self, verdict_lines: list[str]) -> None:
        """All three lines must carry the 'Y' (pass) indicator, not 'N' (fail)."""
        for i, line in enumerate(verdict_lines[:3]):
            parts = line.split(":", 1)
            assert len(parts) == 2, (
                f"Line {i + 1} is malformed (no ':'): {line!r}"
            )
            value = parts[1].strip()
            assert value == "Y", (
                f"verdict_brief.txt line {i + 1} value must be 'Y'; got {value!r}.\n"
                f"Full line: {line!r}"
            )

    def test_dual_lens_key_is_correct(self, verdict_lines: list[str]) -> None:
        """The key on line 1 must be exactly 'DUAL_LENS' (not 'DUAL-LENS' or a typo)."""
        assert len(verdict_lines) >= 1
        key = verdict_lines[0].split(":", 1)[0]
        assert key == "DUAL_LENS", (
            f"Line 1 key must be 'DUAL_LENS'; got {key!r}"
        )

    def test_spin_pct_key_is_correct(self, verdict_lines: list[str]) -> None:
        """The key on line 2 must be exactly 'SPIN_PCT' (not 'SPIN_PERCENT' or a typo)."""
        assert len(verdict_lines) >= 2
        key = verdict_lines[1].split(":", 1)[0]
        assert key == "SPIN_PCT", (
            f"Line 2 key must be 'SPIN_PCT'; got {key!r}"
        )

    def test_market_key_is_correct(self, verdict_lines: list[str]) -> None:
        """The key on line 3 must be exactly 'MARKET'."""
        assert len(verdict_lines) >= 3
        key = verdict_lines[2].split(":", 1)[0]
        assert key == "MARKET", (
            f"Line 3 key must be 'MARKET'; got {key!r}"
        )

    def test_no_n_values_anywhere_in_first_three_lines(self, verdict_lines: list[str]) -> None:
        """None of the three values must be 'N' — that would indicate a failing criterion."""
        for i, line in enumerate(verdict_lines[:3]):
            parts = line.split(":", 1)
            if len(parts) == 2:
                value = parts[1].strip()
                assert value != "N", (
                    f"verdict_brief.txt line {i + 1} has a failing value 'N': {line!r}.\n"
                    "All three criteria must be 'Y' (pass)."
                )

    def test_file_ends_with_newline(self) -> None:
        """verdict_brief.txt must end with a newline — standard POSIX text file format."""
        text = VERDICT_FILE.read_text()
        assert text.endswith("\n"), (
            "verdict_brief.txt must end with a newline character"
        )
